### ISSUE TITLE
Doesn't work with preact v10.16.0

### ISSUE THREAD

**Issue by Nek** [CodyJasonBennett/preact-reconciler#1]
It seems to be broken to me with preact v10.16.0 (v10.15.0 works fine).

My package.json:
```
{
  "name": "0x-protein",
  "version": "0.0.1",
  "description": "Protein vis.",
  "files": [
    "dist"
  ],
  "sideEffects": false,
  "devDependencies": {
    "@preact/preset-vite": "^2.5.0",
    "typescript": "^4.9.5",
    "vite": "^4.1.4"
  },
  "peerDependencies": {
    "preact": ">=10"
  },
  "scripts": {
    "dev": "vite",
    "build": "vite build && tsc"
  },
  "dependencies": {
    "@react-three/cannon": "^6.5.2",
    "@react-three/drei": "^9.79.0",
    "@react-three/fiber": "^8.13.5",
    "preact": "^10.13.0",
    "preact-reconciler": "^0.1.6",
    "three": "^0.154.0"
  }
}
```
Error log from the browser:
```
debug.js:94 Uncaught TypeError: Cannot read properties of null (reading 'b')
    at u.insertBefore (index.mjs?v=91d08b7d:1:987)
    at $ (children.js:297:13)
    at P (children.js:200:14)
    at L (index.js:234:4)
    at P (children.js:133:3)
    at L (index.js:234:4)
    at P (children.js:133:3)
    at L (index.js:234:4)
    at P (children.js:133:3)
    at L (index.js:234:4)
2index.mjs?v=91d08b7d:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'b')
    at u.insertBefore (index.mjs?v=91d08b7d:1:987)
    at $ (children.js:297:13)
    at P (children.js:200:14)
    at L (index.js:234:4)
    at P (children.js:133:3)
    at L (index.js:234:4)
    at P (children.js:133:3)
    at L (index.js:234:4)
    at P (children.js:133:3)
    at L (index.js:234:4)
    ```
    
    As far as I know, this usually happens when there are dupes of preact. I don't see where it's coming from.

**Comment by CodyJasonBennett** [comment]
That release actually caught a bug since TS was inferring fields to be `any` and thus allow null pointers to be passed. For future reference, I have https://github.com/CodyJasonBennett/react-nylon which depends on React and very closely follows React architecture with some improvements for concurrent rendering I intend to upstream.
